package org.example;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.Wait;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CreateNewProjectTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  private WebDriverWait wait;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\selenium\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    wait = new WebDriverWait(driver, 60);
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void createNewProject() {
    driver.get("https://crm.geekbrains.space/");
    driver.manage().window().setSize(new Dimension(712, 680));
    driver.findElement(By.id("prependedInput")).sendKeys("Applanatest1");
    driver.findElement(By.id("prependedInput2")).click();
    driver.findElement(By.cssSelector(".container")).click();
    driver.findElement(By.id("prependedInput2")).sendKeys("Student2020!");
    driver.findElement(By.id("_submit")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".dropdown:nth-child(3) > .unclickable > .title"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.linkText("Все проекты"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".dropdown:nth-child(3) .single:nth-child(4) .title"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".dropdown:nth-child(3) .single:nth-child(4) .title")).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Создать проект")));
    driver.findElement(By.linkText("Создать проект")).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.name("crm_project[name]")));
    driver.findElement(By.name("crm_project[name]")).sendKeys("Проект №" + Math.random());
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".select2-default > .select2-chosen"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }

    {
      WebElement element = driver.findElement(By.id("select2-drop-mask"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    //driver.findElement(By.cssSelector(".lang-ru")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".row"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.xpath("//*[@id=\"select2-drop\"]/ul[2]/li[2]")));
    {
      WebElement element = driver.findElement(By.xpath("//*[@id=\"select2-drop\"]/ul[2]/li[2]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }

    driver.findElement(By.xpath("//*[@id=\"select2-drop\"]/ul[2]/li[2]")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[3]/div[2]/div/select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement dropdown = driver.findElement(By.xpath("//div[3]/div[2]/div/select"));
      dropdown.findElement(By.cssSelector("*[value='1']")).click();
    }
    {
      WebElement element = driver.findElement(By.xpath("//div[4]/div[2]/div/select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement dropdown = driver.findElement(By.xpath("//div[4]/div[2]/div/select"));
      dropdown.findElement(By.cssSelector("*[value='1']")).click();
    }
    {
      WebElement element = driver.findElement(By.xpath("//div[5]/div[2]/div/select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement dropdown = driver.findElement(By.xpath("//div[5]/div[2]/div/select"));
      dropdown.findElement(By.cssSelector("*[value='1']")).click();
    }
    {
      WebElement element = driver.findElement(By.xpath("//div[6]/div[2]/div/select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement dropdown = driver.findElement(By.xpath("//div[6]/div[2]/div/select"));
      dropdown.findElement(By.cssSelector("*[value='93']")).click();
    }
    {
      WebElement element = driver.findElement(By.xpath("//div[7]/div[2]/div/select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement dropdown = driver.findElement(By.xpath("//div[7]/div[2]/div/select"));
      dropdown.findElement(By.cssSelector("*[value='41']")).click();
    }
    {
      WebElement element = driver.findElement(By.xpath("//div[8]/div[2]/div/select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement dropdown = driver.findElement(By.xpath("//div[8]/div[2]/div/select"));
      dropdown.findElement(By.cssSelector("*[value='93']")).click();
    }
    {
      WebElement element = driver.findElement(By.xpath("//div[9]/div[2]/div/select"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement dropdown = driver.findElement(By.xpath("//div[9]/div[2]/div/select"));
      dropdown.findElement(By.cssSelector("*[value='20']")).click();
    }
    {
      WebElement element = driver.findElement(By.xpath("//div[4]/div/div[2]/div/a"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.xpath("//div[4]/div/div[2]/div/a"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//div[4]/div/div[2]/div/a")).click();
    {
      WebElement element = driver.findElement(By.xpath("//*[@id=\"select2-drop\"]/ul[2]/li[7]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//*[@id=\"select2-drop\"]/ul[2]/li[7]")).click();
    {
      WebElement element = driver.findElement(By.xpath("//*[@id=\"mceu_24\"]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.switchTo().frame(0);
    driver.findElement(By.id("tinymce")).click();
    {
      WebElement element = driver.findElement(By.id("tinymce"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>ydydtry</p>'}", element);
    }
    driver.switchTo().defaultContent();
    driver.switchTo().frame(1);
    driver.findElement(By.id("tinymce")).click();
    {
      WebElement element = driver.findElement(By.id("tinymce"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>ydydtry</p>'}", element);
    }
    driver.switchTo().defaultContent();
    driver.switchTo().frame(2);
    driver.findElement(By.id("tinymce")).click();
    {
      WebElement element = driver.findElement(By.id("tinymce"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>ydydtry</p>'}", element);
    }
    driver.switchTo().defaultContent();
    driver.switchTo().frame(3);
    driver.findElement(By.id("tinymce")).click();
    {
      WebElement element = driver.findElement(By.id("tinymce"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<p>ydydtry</p>'}", element);
    }
    driver.switchTo().defaultContent();
    driver.findElement(By.name("crm_project[configManagement]")).click();
    driver.findElement(By.name("crm_project[configManagement]")).sendKeys("oh");
    driver.findElement(By.name("crm_project[skipSpeedChecks]")).click();
    {
      WebElement element = driver.findElement(By.name("crm_project[reportInterval]"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement dropdown = driver.findElement(By.name("crm_project[reportInterval]"));
      dropdown.findElement(By.cssSelector("*[value='month']")).click();
    }

    //сохраниние и удаление созданного проекта

    driver.findElement(By.cssSelector(".dropdown:nth-child(3) > .unclickable > .title")).click();
    driver.findElement(By.cssSelector(".btn-group:nth-child(4) > .btn")).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".filter-item:nth-child(1) > .btn")));
    {
      WebElement element = driver.findElement(By.cssSelector(".filter-item:nth-child(1) > .btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".filter-item:nth-child(1) .filter-criteria-hint")));
    driver.findElement(By.cssSelector(".filter-item:nth-child(1) .filter-criteria-hint")).click();
    driver.findElement(By.name("value")).click();

    // Блок с удалением (не работает)  :(
    /*driver.findElement(By.name("value")).sendKeys("uyfffdddss");
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".filter-update")));
    driver.findElement(By.cssSelector(".filter-update")).click();

    {
      WebElement element = driver.findElement(By.cssSelector(".title-buttons-container"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".title-buttons-container")));
    driver.findElement(By.cssSelector(".title-buttons-container")).click();


    //driver.findElement(By.cssSelector(".mouse-down > .grid-body-cell-name")).click();
    //driver.findElement(By.cssSelector(".title-buttons-container")).click();
    //wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".remove-button")));
    //driver.findElement(By.cssSelector(".remove-button")).click();
    //driver.findElement(By.linkText("Да, удалить")).click();
    //wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Applanatest1 Applanatest1 Applanatest1")));

    /*wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("uyfffdddsslllmmnnbbvcxxz")));
    driver.findElement(By.linkText("uyfffdddsslllmmnnbbvcxxz")).click();

    wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".remove-button")));
    driver.findElement(By.cssSelector(".remove-button")).click();
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.linkText("Да, удалить")));
    driver.findElement(By.linkText("Да, удалить")).click();

    {
      WebElement element = driver.findElement(By.linkText("Applanatest1 Applanatest1 Applanatest1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Applanatest1 Applanatest1 Applanatest1")).click();
    {
      WebElement element = driver.findElement(By.linkText("Выйти"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.linkText("Выйти")).click();
    driver.close();
  }*/
  }
}